"""
AI Brain — Answers questions and controls the PC using Ollama (primary) or Gemini (fallback).
Supports dynamic Python execution generated by the AI for full laptop control.
"""
from __future__ import annotations

import logging
import os
import re

import requests

log = logging.getLogger("jarvis.ai_brain")

OLLAMA_URL = (os.environ.get("OLLAMA_URL") or "http://localhost:11434").rstrip("/")
OLLAMA_MODEL = (os.environ.get("OLLAMA_MODEL") or "qwen3:8b").strip()
GEMINI_API_KEY = (os.environ.get("GEMINI_API_KEY") or "").strip()
GEMINI_MODEL = (os.environ.get("GEMINI_MODEL") or "gemini-1.5-flash").strip()

_SYSTEM_PROMPT = (
    "You are Jarvis, an autonomous AI assistant on a Windows PC.\n"
    "1. For general questions, give concise, conversational replies under 3 sentences. Do not use markdown.\n"
    "2. If the user asks you to perform a system control, computer action, file operation, opening website/app, "
    "typing text, or anything that requires computer automation, you MUST respond in the following format:\n"
    "EXECUTE_PYTHON:\n"
    "<valid python code to perform the task>\n"
    "Inside the code, use standard python packages (os, subprocess, time, shutil, webbrowser) "
    "or pyautogui for GUI actions. Always print() a short confirmation message at the end of the code "
    "so Jarvis can speak it to the user. Do not explain the code, just return the raw text starting with EXECUTE_PYTHON:.\n"
)


def _ask_gemini(query: str) -> str | None:
    if not GEMINI_API_KEY:
        return None
    try:
        url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/"
            f"{GEMINI_MODEL}:generateContent?key={GEMINI_API_KEY}"
        )
        payload = {
            "contents": [
                {"role": "user", "parts": [{"text": f"{_SYSTEM_PROMPT}\n\nUser: {query}"}]}
            ]
        }
        r = requests.post(url, json=payload, timeout=12)
        r.raise_for_status()
        data = r.json()
        text = data["candidates"][0]["content"]["parts"][0]["text"]
        return text.strip()
    except Exception as e:
        log.warning("Gemini failed: %s", e)
        return None


def _ask_ollama(query: str) -> str | None:
    model_to_use = OLLAMA_MODEL
    try:
        r_tags = requests.get(f"{OLLAMA_URL}/api/tags", timeout=2)
        if r_tags.status_code == 200:
            available = [m["name"] for m in r_tags.json().get("models", [])]
            if model_to_use not in available and available:
                matched = next((m for m in available if model_to_use.split(":")[0] in m), available[0])
                model_to_use = matched
                log.info("Configured Ollama model '%s' not found. Using '%s' instead.", OLLAMA_MODEL, model_to_use)
    except Exception as e:
        log.warning("Could not verify Ollama tags: %s", e)

    try:
        r = requests.post(
            f"{OLLAMA_URL}/api/generate",
            json={
                "model": model_to_use,
                "prompt": query,
                "system": _SYSTEM_PROMPT,
                "stream": False,
                "options": {"num_predict": 500, "temperature": 0.2},
            },
            timeout=60,  # Increased timeout for slow system start/CPU runs
        )
        r.raise_for_status()
        text = r.json().get("response", "").strip()
        return text if text else None
    except requests.exceptions.ConnectionError:
        log.warning("Ollama not reachable at %s (is it running?)", OLLAMA_URL)
        return None
    except Exception as e:
        log.warning("Ollama execution failed for model '%s': %s", model_to_use, e)
        return None


def is_ollama_available() -> bool:
    """Quick check if Ollama is running."""
    try:
        r = requests.get(f"{OLLAMA_URL}/api/tags", timeout=2)
        return r.status_code == 200
    except Exception:
        return False


def ask(query: str) -> str:
    """
    Ask a question. Tries Ollama (primary) → Gemini (fallback) → hardcoded message.
    Executes Python scripts generated by the AI for system control.
    """
    # 1. Ollama (offline, local, private - checked first)
    answer = _ask_ollama(query)
    if answer:
        log.info("AI answer via Ollama.")
    else:
        # 2. Gemini (online, fallback)
        answer = _ask_gemini(query)
        if answer:
            log.info("AI answer via Gemini.")

    if not answer:
        log.warning("Both AI providers unavailable.")
        return (
            "I couldn't reach any AI right now. "
            "Please check your internet or make sure Ollama is running."
        )

    # 3. Handle Python code execution generated by AI
    if "EXECUTE_PYTHON:" in answer:
        import sys
        import io

        code_block = answer.split("EXECUTE_PYTHON:")[1].strip()
        # Clean markdown fences
        code_block = re.sub(r"^```python\n?", "", code_block)
        code_block = re.sub(r"^```\n?", "", code_block)
        code_block = re.sub(r"\n?```$", "", code_block)

        log.info("AI requested system control execution. Running Python block:\n%s", code_block)
        
        # Expose useful modules to execution context
        import os
        import subprocess
        import time
        import shutil
        import webbrowser
        try:
            import pyautogui
        except ImportError:
            pyautogui = None

        loc = {
            "os": os,
            "subprocess": subprocess,
            "time": time,
            "shutil": shutil,
            "webbrowser": webbrowser,
            "pyautogui": pyautogui,
        }

        old_stdout = sys.stdout
        new_stdout = io.StringIO()
        sys.stdout = new_stdout

        try:
            exec(code_block, globals(), loc)
            sys.stdout = old_stdout
            output = new_stdout.getvalue().strip()
            return output if output else "Action executed successfully, sir."
        except Exception as e:
            sys.stdout = old_stdout
            log.error("Execution failed: %s", e)
            return f"Action execution failed: {e}."

    # Strip any potential leftover markdown formatting for plain TTS speaking
    clean_answer = re.sub(r"\*+", "", answer).strip()
    return clean_answer
