"""
AI Brain — Answers questions and controls the PC using Ollama (primary) or Gemini (fallback).
Supports dynamic Python execution generated by the AI for full laptop control.
Supports persistent conversational history across sessions.
"""
from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path
from datetime import datetime

import requests

log = logging.getLogger("jarvis.ai_brain")

OLLAMA_URL = (os.environ.get("OLLAMA_URL") or "http://localhost:11434").rstrip("/")
OLLAMA_MODEL = (os.environ.get("OLLAMA_MODEL") or "qwen3:8b").strip()
GEMINI_API_KEY = (os.environ.get("GEMINI_API_KEY") or "").strip()
GEMINI_MODEL = (os.environ.get("GEMINI_MODEL") or "gemini-2.0-flash").strip()
GEMINI_FALLBACK_MODELS = ["gemini-2.0-flash", "gemini-1.5-flash", "gemini-1.5-pro", "gemini-pro"]
XAI_API_KEY = (os.environ.get("XAI_API_KEY") or "").strip()

# Persistent history file
HISTORY_FILE = Path(os.environ.get("USERPROFILE", Path.home())) / ".jarvis_history.json"
MAX_HISTORY_TURNS = 20  # Keep last N turns in context

_SYSTEM_PROMPT = (
    "You are Jarvis, an autonomous AI assistant on a Windows PC.\n"
    "1. For general questions, give concise, conversational replies under 3 sentences. Do not use markdown.\n"
    "2. If the user asks you to perform a system control, computer action, file operation, opening website/app, "
    "typing text, or anything that requires computer automation, you MUST respond in the following format:\n"
    "EXECUTE_PYTHON:\n"
    "<valid python code to perform the task>\n"
    "Inside the code, use standard python packages (os, subprocess, time, shutil, webbrowser) "
    "or pyautogui for GUI actions. Always print() a short confirmation message at the end of the code "
    "so Jarvis can speak it to the user. Do not explain the code, just return the raw text starting with EXECUTE_PYTHON:.\n"
)


# ─── History management ────────────────────────────────────────────────────────

def _load_history() -> list[dict]:
    """Load conversation history from disk."""
    try:
        if HISTORY_FILE.exists():
            data = json.loads(HISTORY_FILE.read_text(encoding="utf-8"))
            if isinstance(data, list):
                return data[-MAX_HISTORY_TURNS:]
    except Exception as e:
        log.warning("History load error: %s", e)
    return []


def _save_history(history: list[dict]) -> None:
    """Save conversation history to disk."""
    try:
        # Keep only last MAX_HISTORY_TURNS
        trimmed = history[-MAX_HISTORY_TURNS:]
        HISTORY_FILE.write_text(
            json.dumps(trimmed, indent=2, ensure_ascii=False), encoding="utf-8"
        )
    except Exception as e:
        log.warning("History save error: %s", e)


def _append_to_history(role: str, content: str) -> None:
    """Append a single turn to persistent history."""
    history = _load_history()
    history.append({
        "role": role,
        "content": content,
        "timestamp": datetime.now().isoformat(timespec="seconds"),
    })
    _save_history(history)


def clear_history() -> str:
    """Clear conversation history."""
    try:
        _save_history([])
        return "Conversation history cleared, sir."
    except Exception as e:
        return f"Could not clear history: {e}"


def _build_context_prompt(query: str) -> str:
    """Build a prompt that includes recent history for context."""
    history = _load_history()
    # Exclude last user turn (current query) to prevent duplicate User prompt rendering
    history_turns = history[:-1] if (history and history[-1]["role"] == "user") else history
    if not history_turns:
        return f"{_SYSTEM_PROMPT}\n\nUser: {query}"

    context_lines = []
    for turn in history_turns[-10:]:
        role_label = "User" if turn["role"] == "user" else "Jarvis"
        context_lines.append(f"{role_label}: {turn['content']}")

    context = "\n".join(context_lines)
    return f"{_SYSTEM_PROMPT}\n\nConversation history:\n{context}\n\nUser: {query}"


# ─── AI backends ──────────────────────────────────────────────────────────────

def _ask_gemini(query: str) -> str | None:
    if not GEMINI_API_KEY:
        return None
    # Build contents with history for Gemini
    history = _load_history()
    # Exclude last user turn (current query) to prevent consecutive 'user' messages
    history_turns = history[:-1] if (history and history[-1]["role"] == "user") else history
    
    contents = []
    for turn in history_turns[-8:]:
        if not turn.get("content"):
            continue
        contents.append({
            "role": "user" if turn["role"] == "user" else "model",
            "parts": [{"text": turn["content"]}]
        })
    contents.append({"role": "user", "parts": [{"text": f"{_SYSTEM_PROMPT}\n\nUser: {query}"}]})
    payload = {"contents": contents}

    # Try each model in order until one works
    models_to_try = [GEMINI_MODEL] + [m for m in GEMINI_FALLBACK_MODELS if m != GEMINI_MODEL]
    extended_models = []
    for m in models_to_try:
        if m not in extended_models:
            extended_models.append(m)
        latest = f"{m}-latest" if not m.endswith("-latest") else m
        if latest not in extended_models:
            extended_models.append(latest)

    for model in extended_models:
        for api_ver in ["v1", "v1beta"]:
            try:
                url = (
                    f"https://generativelanguage.googleapis.com/{api_ver}/models/"
                    f"{model}:generateContent?key={GEMINI_API_KEY}"
                )
                r = requests.post(url, json=payload, timeout=12)
                if r.status_code == 404:
                    continue  # Try next endpoint version or next model
                r.raise_for_status()
                data = r.json()
                text = data["candidates"][0]["content"]["parts"][0]["text"]
                return text.strip()
            except Exception as e:
                log.warning("Gemini failed for model '%s' on %s: %s", model, api_ver, e)
                continue
    return None


def _ask_xai(query: str) -> str | None:
    if not XAI_API_KEY:
        return None
    try:
        url = "https://api.x.ai/v1/chat/completions"
        headers = {
            "Authorization": f"Bearer {XAI_API_KEY}",
            "Content-Type": "application/json"
        }
        
        history = _load_history()
        # Exclude last user turn (current query) to prevent consecutive 'user' messages
        history_turns = history[:-1] if (history and history[-1]["role"] == "user") else history
        
        messages = [{"role": "system", "content": _SYSTEM_PROMPT}]
        for turn in history_turns[-8:]:
            if not turn.get("content"):
                continue
            messages.append({
                "role": "user" if turn["role"] == "user" else "assistant",
                "content": turn["content"]
            })
        messages.append({"role": "user", "content": query})
        
        payload = {
            "model": "grok-beta",
            "messages": messages,
            "temperature": 0.2
        }
        
        r = requests.post(url, json=payload, headers=headers, timeout=12)
        r.raise_for_status()
        return r.json()["choices"][0]["message"]["content"].strip()
    except Exception as e:
        log.warning("xAI API failed: %s", e)
        return None



def _ask_ollama(query: str) -> str | None:
    model_to_use = OLLAMA_MODEL
    # Quick availability check — skip entirely if Ollama is not running
    try:
        r_tags = requests.get(f"{OLLAMA_URL}/api/tags", timeout=1.5)
        if r_tags.status_code != 200:
            log.warning("Ollama server returned status code %s, skipping.", r_tags.status_code)
            return None
        available = [m["name"] for m in r_tags.json().get("models", [])]
        if model_to_use not in available and available:
            matched = next((m for m in available if model_to_use.split(":")[0] in m), available[0])
            model_to_use = matched
            log.info("Configured Ollama model '%s' not found. Using '%s' instead.", OLLAMA_MODEL, model_to_use)
        elif not available:
            log.warning("Ollama has no models downloaded! Please run 'ollama pull qwen2.5:7b' in cmd.")
            return None
    except Exception as e:
        log.warning("Ollama not reachable on %s: %s", OLLAMA_URL, e)
        return None

    # Build prompt with history context
    prompt_with_history = _build_context_prompt(query)

    try:
        r = requests.post(
            f"{OLLAMA_URL}/api/generate",
            json={
                "model": model_to_use,
                "prompt": prompt_with_history,
                "system": _SYSTEM_PROMPT,
                "stream": False,
                "options": {"num_predict": 1500, "temperature": 0.2},
            },
            timeout=45,
        )
        r.raise_for_status()
        text = r.json().get("response", "").strip()
        return text if text else None
    except requests.exceptions.ConnectionError:
        log.warning("Ollama not reachable at %s (is it running?)", OLLAMA_URL)
        return None
    except Exception as e:
        log.warning("Ollama execution failed for model '%s': %s", model_to_use, e)
        return None



def is_ollama_available() -> bool:
    """Quick check if Ollama is running."""
    try:
        r = requests.get(f"{OLLAMA_URL}/api/tags", timeout=2)
        return r.status_code == 200
    except Exception:
        return False


def ask(query: str) -> str:
    """
    Ask a question. Tries Ollama (primary) → Gemini (fallback) → hardcoded message.
    Executes Python scripts generated by the AI for system control.
    Saves conversation turns to persistent history.
    """
    # Save user query to history
    _append_to_history("user", query)

    # 1. Ollama (offline, local, private - checked first)
    answer = _ask_ollama(query)
    if answer:
        log.info("AI answer via Ollama.")
    else:
        # 2. xAI Grok (primary online fallback)
        answer = _ask_xai(query)
        if answer:
            log.info("AI answer via xAI.")
        else:
            # 3. Gemini (secondary online fallback)
            answer = _ask_gemini(query)
            if answer:
                log.info("AI answer via Gemini.")

    if not answer:
        log.warning("Both AI providers unavailable.")
        # If the query is about live information, let's proactively open a google search!
        t_lower = query.lower()
        live_keywords = ["weather", "score", "vs", "exam", "match", "news", "today", "tomorrow", "result", "time", "date", "status", "who is", "what is"]
        if any(kw in t_lower for kw in live_keywords):
            try:
                import webbrowser
                import urllib.parse
                webbrowser.open(f"https://www.google.com/search?q={urllib.parse.quote(query)}")
                return f"I couldn't reach the AI right now, so I opened a Google search for '{query}' on your browser, sir."
            except Exception:
                pass
        return (
            "I couldn't reach any AI right now. "
            "Please check your internet or make sure Ollama is running."
        )

    # 3. Handle Python code execution generated by AI
    if "EXECUTE_PYTHON:" in answer:
        import sys
        import io

        code_block = answer.split("EXECUTE_PYTHON:")[1].strip()
        # Clean markdown fences
        code_block = re.sub(r"^```python\n?", "", code_block)
        code_block = re.sub(r"^```\n?", "", code_block)
        code_block = re.sub(r"\n?```$", "", code_block)

        log.info("AI requested system control execution. Running Python block:\n%s", code_block)

        import os as _os
        import subprocess as _subprocess
        import time as _time
        import shutil as _shutil
        import webbrowser as _webbrowser
        try:
            import pyautogui as _pyautogui
        except ImportError:
            _pyautogui = None

        loc = {
            "os": _os,
            "subprocess": _subprocess,
            "time": _time,
            "shutil": _shutil,
            "webbrowser": _webbrowser,
            "pyautogui": _pyautogui,
        }

        old_stdout = sys.stdout
        new_stdout = io.StringIO()
        sys.stdout = new_stdout

        try:
            exec(code_block, globals(), loc)
            sys.stdout = old_stdout
            output = new_stdout.getvalue().strip()
            result_text = output if output else "Action executed successfully, sir."
            _append_to_history("assistant", result_text)
            return result_text
        except Exception as e:
            sys.stdout = old_stdout
            log.error("Execution failed: %s", e)
            err_text = f"Action execution failed: {e}."
            _append_to_history("assistant", err_text)
            return err_text

    # Strip any potential leftover markdown formatting for plain TTS speaking
    clean_answer = re.sub(r"\*+", "", answer).strip()
    _append_to_history("assistant", clean_answer)
    return clean_answer


def warmup_ollama() -> None:
    """Warm up the Ollama model in the background on startup."""
    def _warmup():
        try:
            r_tags = requests.get(f"{OLLAMA_URL}/api/tags", timeout=2)
            if r_tags.status_code == 200:
                available = [m["name"] for m in r_tags.json().get("models", [])]
                model_to_use = OLLAMA_MODEL
                if model_to_use not in available and available:
                    matched = next((m for m in available if model_to_use.split(":")[0] in m), available[0])
                    model_to_use = matched
                log.info("Warming up Ollama model '%s' in background...", model_to_use)
                
                # Send empty prompt to load the model into memory
                requests.post(
                    f"{OLLAMA_URL}/api/generate",
                    json={"model": model_to_use, "prompt": "", "stream": False},
                    timeout=30
                )
                log.info("Ollama model '%s' warmed up successfully.", model_to_use)
        except Exception as e:
            log.debug("Ollama warmup failed: %s", e)
            
    import threading
    threading.Thread(target=_warmup, daemon=True).start()

# Initialize warmup on import
warmup_ollama()


def _ask_ollama_raw(prompt: str) -> str | None:
    model_to_use = OLLAMA_MODEL
    try:
        r_tags = requests.get(f"{OLLAMA_URL}/api/tags", timeout=1.5)
        if r_tags.status_code != 200:
            return None
        available = [m["name"] for m in r_tags.json().get("models", [])]
        if model_to_use not in available and available:
            matched = next((m for m in available if model_to_use.split(":")[0] in m), available[0])
            model_to_use = matched
    except Exception:
        return None

    _CODE_SYSTEM_PROMPT = (
        "You are an expert software developer. "
        "When given a task, output ONLY the raw source code content — no explanations, "
        "no markdown code fences, no backticks, no EXECUTE_PYTHON prefix. "
        "Just the clean, complete, working code."
    )
    try:
        r = requests.post(
            f"{OLLAMA_URL}/api/generate",
            json={
                "model": model_to_use,
                "prompt": prompt,
                "system": _CODE_SYSTEM_PROMPT,
                "stream": False,
                "options": {"num_predict": 2000, "temperature": 0.2},
            },
            timeout=40,
        )
        r.raise_for_status()
        return r.json().get("response", "").strip()
    except Exception as e:
        log.warning("Ollama raw generation failed: %s", e)
        return None


def _ask_xai_raw(prompt: str) -> str | None:
    if not XAI_API_KEY:
        return None
    try:
        url = "https://api.x.ai/v1/chat/completions"
        headers = {
            "Authorization": f"Bearer {XAI_API_KEY}",
            "Content-Type": "application/json"
        }
        payload = {
            "model": "grok-beta",
            "messages": [
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.2
        }
        r = requests.post(url, json=payload, headers=headers, timeout=25)
        r.raise_for_status()
        return r.json()["choices"][0]["message"]["content"].strip()
    except Exception as e:
        log.warning("xAI raw API failed: %s", e)
        return None


def _ask_gemini_raw(prompt: str) -> str | None:
    if not GEMINI_API_KEY:
        return None
    
    models_to_try = [GEMINI_MODEL] + [m for m in GEMINI_FALLBACK_MODELS if m != GEMINI_MODEL]
    extended_models = []
    for m in models_to_try:
        if m not in extended_models:
            extended_models.append(m)
        latest = f"{m}-latest" if not m.endswith("-latest") else m
        if latest not in extended_models:
            extended_models.append(latest)

    for model in extended_models:
        for api_ver in ["v1", "v1beta"]:
            try:
                url = (
                    f"https://generativelanguage.googleapis.com/{api_ver}/models/"
                    f"{model}:generateContent?key={GEMINI_API_KEY}"
                )
                payload = {
                    "contents": [
                        {"role": "user", "parts": [{"text": f"{_SYSTEM_PROMPT}\n\nUser: {prompt}"}]}
                    ]
                }
                r = requests.post(url, json=payload, timeout=25)
                if r.status_code == 404:
                    continue
                r.raise_for_status()
                data = r.json()
                return data["candidates"][0]["content"]["parts"][0]["text"].strip()
            except Exception as e:
                log.warning("Gemini raw failed for model '%s' on %s: %s", model, api_ver, e)
                continue
    return None


def generate_text_raw(prompt: str) -> str | None:
    """Core raw generation (no conversation history) using Ollama -> xAI -> Gemini."""
    res = _ask_ollama_raw(prompt)
    if res:
        return res
    res = _ask_xai_raw(prompt)
    if res:
        return res
    return _ask_gemini_raw(prompt)


